### ISSUE TITLE
Blueprints Bug: Logo and Iconography Guidelines Does Not Display Images

### ISSUE THREAD

**Issue by naoki-evan-hisamoto** [liferay-design/liferay.design#651] opened 2020-01-24 19:54 UTC
**Describe the bug**
The page shows the default placeholder image instead of an image for the "Avoid" section of logo and iconography guidelines. The "Do, Don't, and Avoid" sections also seem to be misaligned. 

**To Reproduce**

1. Go to "https://liferay.design/blueprints/guidelines/logo-usage/"
2. Scroll down to "Usage Guidelines for Liferay Logos"
3. See error

or 

1. Go to "https://liferay.design/blueprints/guidelines/iconography/"
2. Scroll down to "General Rules"
3. See error

**Expected behavior**
I expect the proper images to show up and the sections to be aligned.

**Screenshots**

![image](https://user-images.githubusercontent.com/28310489/73099309-179bd700-3ea0-11ea-84b5-f1225c4239ac.png)

![image](https://user-images.githubusercontent.com/28310489/73099318-1ec2e500-3ea0-11ea-869f-b390fe7d528e.png)

**Desktop (please complete the following information):**
-   MacOS Catalina 10.15.2
-   Chrome
-   Version 79.0.3945.130 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by plhnk** [comment] 2020-01-24 20:39
Thanks @naoki-evan-hisamoto! I suspect this may have come when we added the "avoid" option... we'll look into it!

cc @laugardie do you have any ideas off the top of your head?

**Comment by laugardie** [comment] 2020-01-27 10:11
Hey @plhnk I have reproduced the behaviour and I think that the sections are misaligned because the images have different sizes. And regarding to the images that are not displaying, I think that the source path is not correct as it appears as /undefined.

**Comment by plhnk** [comment] 2020-01-27 15:56
Yes — it looks like the component still renders the "Avoid" div even though there wasn't an 'avoid' image specified in the markdown:
![image](https://user-images.githubusercontent.com/10226086/73188763-3684ae00-40d8-11ea-8673-57e48a4a4f19.png)

One way to solve this would be to use a ternary operator to [conditionally render](https://reactjs.org/docs/conditional-rendering.html#inline-if-else-with-conditional-operator) each part of this component — i.e. if a user only wants to have "good" and "avoid" that is possible.

If you're interested in working on it, you could reference the `<Container>` component — the lines I've highlighted basically say — if there's a heading fed into the component, then render the `<Heading>`, else render `null`:
![image](https://user-images.githubusercontent.com/10226086/73189829-e4448c80-40d9-11ea-8e27-fbf8439a53f0.png)

[There are other ways to do it](https://www.robinwieruch.de/conditional-rendering-react), this one might be the most straightforward.

Let me know if it makes sense and you want to take a crack at it!

**Comment by plhnk** [comment] 2020-02-01 00:09
fixed in #657

**Comment by plhnk** [comment] 2020-02-01 00:09
thanks @laugardie great work!

**Closed by plhnk** 2020-02-01 00:09 UTC
Labels: blueprints, bug, lexicon
